### ISSUE TITLE
YubicoClient.verify never throws YubicoVerificationException when server is unreachable

### ISSUE THREAD

**Issue by Ghilteras** [Yubico/yubico-java-client#18]
Hi, according to the documentation here about the verify method I see that it should throw a `YubicoVerificationException` when the server is unreachable.

https://github.com/Yubico/yubico-java-client/blob/bebebc6ab1635a993444c80f342d8cc9eeec921b/v2client/src/main/java/com/yubico/client/v2/YubicoClient.java#L66

Now this code should throw said exception, but it does not throw anything; the `VerificationResponse` is simply `null`. Am I missing something?

This is the snippet that reproduces it
```java
YubicoClient yubicoClient = YubicoClient.getClient(this.clientId, this.secretKey);
String[] fake_servers = new String[]{"https://api.wrong.server/wsapi/2.0/verify"};
yubicoClient.setWsapiUrls(fake_servers);
VerificationResponse response = yubicoClient.verify(otp_string)
```

**Comment by emlun** [comment]
Hi! Thanks for the report, but I'm unable to reproduce this behaviour even with your code snippet. Specifically, it looks to me like it should be impossible for `YubicoClientImpl.verify(String otp)` to return `null`, because it should throw a `NullPointerException` before reaching the return statement:

https://github.com/Yubico/yubico-java-client/blob/master/v2client/src/main/java/com/yubico/client/v2/impl/YubicoClientImpl.java#L133-L149

Which version of the library are you using?

**Comment by emlun** [comment]
That's not a connection error - you're passing an invalid value for the `otp` parameter.

I found a test that does approximately what you're trying to do: https://github.com/Yubico/yubico-java-client/blob/master/v2client/src/test/java/com/yubico/client/v2/YubicoClientTest.java#L137-L145
The code in this test does throw `YubicoVerificationException` as expected, although strictly it's an "unknown host" error and not a "host unreachable" error. That shouldn't make a difference.

**Comment by Ghilteras** [comment]
Is the connectivity of the validation server not checked before the actual `otp` parameter? Is the Client running some pre-checks before issuing the request to the Yubicloud API?

**Comment by emlun** [comment]
Yes, [the client checks the OTP format first of all][1]. The connectivity check is the actual execution of the request.

[1]: https://github.com/Yubico/yubico-java-client/blob/bebebc6ab1635a993444c80f342d8cc9eeec921b/v2client/src/main/java/com/yubico/client/v2/impl/YubicoClientImpl.java#L102-L104

**Comment by emlun** [comment]
I'm assuming the questions here have been answered - you're welcome to re-open the issue if there's anything else you need.
